### PR TITLE
Update for 0.3.0

### PR DESCRIPTION
**Pull request by ResidentMario**

### CODE REVIEW

**Comment by ResidentMario** [comment]
@Filipe I've made a minor version incrementation (to address some changes in the just-released `matplotlib 2.0.0` defaults), and it's now failing to build on both platforms. What's the next step?

**Comment by ocefpaf** [comment]
It is not your fault. I am updating the whole stack to use icu 58.*. As
soon as I finish that error should go away b/c the right versions of the
deps will be downloaded.

The gdal PR is already building. I will ping you once that is done so you
can restart the CIs here.

PS: my github handle is @ocefpaf ;-p

**Comment by ocefpaf** [comment]
@ResidentMario I restarted the CIs here and Linux is passing, OS X should pass too. Feel free to merge whenever you think this is ready.

**Comment by ResidentMario** [comment]
Gotcha. This also makes me realize that changes to sub-recipes can break recipes built on top of them. I guess that's fine, since only the recipe authors are affected. I think you should add that to Gotchas page, though.

**Comment by ocefpaf** [comment]
> I think you should add that to Gotchas page, though.

Indeed. (I actually need to write that page first :smile:)

**Pull request merged**
