### PR TITLE
0.1.1 recipe w/ hard version dependency

### PR DESCRIPTION
**Pull request by ResidentMario**
Cf. [here](https://github.com/conda-forge/kealib-feedstock/issues/15) for why this is necessary. This is a "dumb" but possibly good-enough way of fixing this issue

### CODE REVIEW

**Comment by ResidentMario** [comment]
@ocefpaf I need `conda` to pull and build with `gdal 2.1.4` or `gdal 2.2.*`, per our discussion [on the issue I opened on `kealib`](https://github.com/conda-forge/kealib-feedstock/issues/15#issuecomment-336784235).

You said the builder was mysteriously pulling `2.1.3` instead, which hasn't been re-built for compatibility with `kealib`. So I figured specifying `gdal >=2.1.4` in the recipe would do the trick.

Much to my surprise, `conda` is solving this recipe with a [2.1.3 version](https://travis-ci.org/conda-forge/geoplot-feedstock/jobs/288094247#L318)!

This leaves me very confused. I thought the whole point of specifying build dependencies was that `conda` would error out if it failed to meet them. Any insight you can share on this?

**Comment by ocefpaf** [comment]
> Much to my surprise, `conda` is solving this recipe with a [2.1.3 version](https://travis-ci.org/conda-forge/geoplot-feedstock/jobs/288094247#L318)!

conda solver surprises us all the time :unamused: 

I'll investigate the dependency chain and see how we can "force" conda to do the right thing there.
(It might take a while, I am away from office and with limited connection.)

**Comment by ResidentMario** [comment]
Argh! That's incredible! Alright, I understand, thanks for your help.

**Comment by ocefpaf** [comment]
superseded by #3

**Pull request closed without merging**
